const comments = [
  {
    postId: 1,
    id: 1,
    name: "11giat sapiente dolorum",
    email: "serg@ukr.net",
    body: "11omnis aspernatur aliquid nobis magnam recusandae laboriosam iure, quasi",
  },
  {
    postId: 1,
    id: 2,
    name: "12giat sapiente dolorum",
    email: "serg@ukr.net",
    body: "12omnis aspernatur aliquid nobis magnam recusandae laboriosam iure, quasi",
  },
  {
    postId: 1,
    id: 3,
    name: "13giat sapiente dolorum",
    email: "serg@ukr.net",
    body: "13omnis aspernatur aliquid nobis magnam recusandae laboriosam iure, quasi",
  },
  {
    postId: 1,
    id: 4,
    name: "14giat sapiente dolorum",
    email: "serg@ukr.net",
    body: "14omnis aspernatur aliquid nobis magnam recusandae laboriosam iure, quasi",
  },

  {
    postId: 2,
    id: 1,
    name: "21giat sapiente dolorum",
    email: "ivan@ukr.net",
    body: "21omnis aspernatur aliquid nobis magnam recusandae laboriosam iure, quasi",
  },
  {
    postId: 2,
    id: 2,
    name: "22giat sapiente dolorum",
    email: "ivan@ukr.net",
    body: "22omnis aspernatur aliquid nobis magnam recusandae laboriosam iure, quasi",
  },
  {
    postId: 2,
    id: 3,
    name: "23giat sapiente dolorum",
    email: "ivan@ukr.net",
    body: "23omnis aspernatur aliquid nobis magnam recusandae laboriosam iure, quasi",
  },
  {
    postId: 2,
    id: 4,
    name: "24giat sapiente dolorum",
    email: "ivan@ukr.net",
    body: "24omnis aspernatur aliquid nobis magnam recusandae laboriosam iure, quasi",
  },

  {
    postId: 3,
    id: 1,
    name: "31giat sapiente dolorum",
    email: "svetik@ukr.net",
    body: "31omnis aspernatur aliquid nobis magnam recusandae laboriosam iure, quasi",
  },
  {
    postId: 3,
    id: 2,
    name: "32giat sapiente dolorum",
    email: "svetik@ukr.net",
    body: "32omnis aspernatur aliquid nobis magnam recusandae laboriosam iure, quasi",
  },
  {
    postId: 3,
    id: 3,
    name: "33giat sapiente dolorum",
    email: "svetik@ukr.net",
    body: "33omnis aspernatur aliquid nobis magnam recusandae laboriosam iure, quasi",
  },
  {
    postId: 3,
    id: 4,
    name: "34giat sapiente dolorum",
    email: "svetik@ukr.net",
    body: "34omnis aspernatur aliquid nobis magnam recusandae laboriosam iure, quasi",
  },

  {
    postId: 4,
    id: 1,
    name: "41giat sapiente dolorum",
    email: "svetik@ukr.net",
    body: "41omnis aspernatur aliquid nobis magnam recusandae laboriosam iure, quasi",
  },
  {
    postId: 4,
    id: 2,
    name: "42giat sapiente dolorum",
    email: "svetik@ukr.net",
    body: "42omnis aspernatur aliquid nobis magnam recusandae laboriosam iure, quasi",
  },
  {
    postId: 4,
    id: 3,
    name: "43giat sapiente dolorum",
    email: "svetik@ukr.net",
    body: "43omnis aspernatur aliquid nobis magnam recusandae laboriosam iure, quasi",
  },
  {
    postId: 4,
    id: 4,
    name: "44giat sapiente dolorum",
    email: "svetik@ukr.net",
    body: "44omnis aspernatur aliquid nobis magnam recusandae laboriosam iure, quasi",
  },
];
